### PR TITLE
Add custom condition

### PR DESCRIPTION
**Pull request by pellejacobs**
For my specific use case, I needed more control over the conditions on which tiles can access a specific tile. 

If you think this is out of scope for this project, you can just close this PR 😄

### CODE REVIEW

**Comment by prettymuchbryce** [comment]
Sorry for the long delay on this. I'm wondering if we can actually get rid of the directional condition in favor of this PR given that it can be solved by downstream projects if given the tool of the custom condition.

**Comment by pellejacobs** [comment]
That seems to make sense. I'll see if I find this weekend some time to figure that out 😄

**Comment by mihaimetal** [comment]
This looks nice. Why wasn't it merged?

**Comment by pellejacobs** [comment]
Closing as I haven't touched this code in 7 years. If anyone is curious, don't hesitate to pick this up!

**Pull request closed without merging**
