### PR TITLE
Fix for Issue #43 (add ci)

### PR DESCRIPTION
**Pull request by esromneb**
This adds a travis.yml config.  In order to get this to work you need to go to https://travis-ci.com/ and make a free account with your github. When they ask for access, just give them access to easystarjs repo. After that you will be able to do builds with each commit.
If you want to see the what the builds on my fork look like, see here: https://travis-ci.com/github/esromneb/easystarjs
I've added builds for version 8-14 as well as node.  It seems like something in karma doesn't work in node 15 right now.
After you make your account, go to your build page on travis-ci.com click on the "build passing" badge. Select format of "markdown" and then paste that into the top of your README.md. this will add a badge to your project.

### CODE REVIEW

**Comment by prettymuchbryce** [comment]
Thanks for your contribution! Is there a reason why we should use `travis-ci` over GitHub Actions? I think the original issue was created before this feature existed natively in GitHub.

**Comment by esromneb** [comment]
No reason. I will re-do this with github actions and then re-submit

**Comment by prettymuchbryce** [comment]
Thanks. Sorry for the confusion. This project is definitely due for some issue / PR cleanup. 😖

**Comment by esromneb** [comment]
No problem, I am happy to contribute.  This project is allowing me to make my dream RTS (slowly).  Maybe I'll finish one day!  Thanks again

**Pull request closed without merging**
