### PR TITLE
Add benchmarks

### PR DESCRIPTION
**Pull request by sbj42**
This patch adds a simple benchmark suite using karma-benchmark.  A separate karma configuration file is necessary, to separate the unit tests from the benchmarks.  `npm run benchmark` to start the karma server on the benchmark suite.

There are two kinds of benchmarks at the moment:  One is maze-like, so the search will be deep but narrow.  The other is a mostly open field, so the search will be short but with more branches.
    
For both cases, the benchmarks are run three different ways: With no diagonals, diagonals but no corner-cutting, and diagonals with corner-cutting.

All of these benchmarks use `enableSync`.  They do not use `setAdditionalPointCost`, `setDirectionalCondition`, or `avoidAdditionalPoint`.

When I ran these benchmarks in `Chrome 56.0.2924 (Windows 10 0.0.0)`, I got the following results (but of course they'll differ from environment to environment):
```
                        EasyStar.js
- 10x10 maze no diagonals                      3799 ops/sec
- 10x10 maze diagonals but no corner-cutting   2716 ops/sec
- 10x10 maze diagonals and corner-cutting      2523 ops/sec
- 10x10 field no diagonals                     3319 ops/sec
- 10x10 field diagonals but no corner-cutting  6108 ops/sec
- 10x10 field diagonals and corner-cutting     6875 ops/sec
```

### CODE REVIEW

**Comment by prettymuchbryce** [comment]
I like the idea of having benchmarks, especially if it can make it easier for us to tell if there has been some major change in performance between changes.

Am I right in assuming a single `op` is considered to be one complete `findPath()`?

Do you know why I might be seeing this error when trying to run them?

```
- 10x10 maze no diagonals                      2189 ops/sec
- 10x10 maze diagonals but no corner-cutting   1954 ops/sec
- 10x10 maze diagonals and corner-cutting      1930 ops/sec
- 10x10 field no diagonals                     1993 ops/sec
- 10x10 field diagonals but no corner-cutting  1997 ops/sec
Chrome 56.0.2924 (Mac OS X 10.12.3) ERROR
  Uncaught RangeError: Maximum call stack size exceeded
  at /Users/bryceneal/projects/sbj42easystar/bin/easystar-0.3.1.js:270
```

Also do you think it makes sense to run these in node and not require a web browser? I was also thinking of eventually migrating the other tests to node to make it easier to CI.

**Comment by sbj42** [comment]
Yeah I was seeing that myself, the last commit should fix it.  I think `karma-benchmark` (or maybe benchmarkjs) assumes that when you resolve the `deferred`, you did it after some timeout, because it immediately calls the next benchmark.

That means if the benchmark is fast enough you blow out the stack before it finishes.  So I just switched them all to synchronous benchmark functions.

**Comment by sbj42** [comment]
It probably doesn't make a big difference which test framework you go with, but maybe it's just slightly easier for someone to get on board if they can just `npm test` and don't have to fiddle with a browser.

**Comment by sbj42** [comment]
> Am I right in assuming a single op is considered to be one complete findPath()?

Yes.

FYI, I set up the benchmarking because I think I see some easy opportunities for performance improvements.  Mainly in avoiding the `something[x + '_' + y]` pattern - string concatenation for a combined lookup seems to be slower than two separate lookups.

**Comment by prettymuchbryce** [comment]
Nice it seems better now.

```
                        EasyStar.js
- 10x10 maze no diagonals                      4003 ops/sec
- 10x10 maze diagonals but no corner-cutting   3101 ops/sec
- 10x10 maze diagonals and corner-cutting      3028 ops/sec
- 10x10 field no diagonals                     3822 ops/sec
- 10x10 field diagonals but no corner-cutting  7166 ops/sec
- 10x10 field diagonals and corner-cutting     8378 ops/sec

                        EasyStar.js
- 10x10 maze no diagonals                      4216 ops/sec
- 10x10 maze diagonals but no corner-cutting   3125 ops/sec
- 10x10 maze diagonals and corner-cutting      2950 ops/sec
- 10x10 field no diagonals                     3642 ops/sec
- 10x10 field diagonals but no corner-cutting  6999 ops/sec
- 10x10 field diagonals and corner-cutting     8526 ops/sec

                        EasyStar.js
- 10x10 maze no diagonals                      3805 ops/sec
- 10x10 maze diagonals but no corner-cutting   3143 ops/sec
- 10x10 maze diagonals and corner-cutting      3009 ops/sec
- 10x10 field no diagonals                     3818 ops/sec
- 10x10 field diagonals but no corner-cutting  7265 ops/sec
- 10x10 field diagonals and corner-cutting     8430 ops/sec
```

If you have ideas around quick performance wins I'm all for that. 👍

**Comment by prettymuchbryce** [comment]
Kind of interesting that the performance varies quite a bit between tests.

**Comment by sbj42** [comment]
Yeah benchmarking is a dark art.  As far as I can tell you can only judge the performance by the general order of magnitude.

**Comment by sbj42** [comment]
I think you'll want at least one "big" grid benchmark, to make sure any performance improvements don't only help with little grids.  Let me add one of those before you merge this.

**Comment by sbj42** [comment]
Ok I'm all set here.

Not sure if I did the fetch right to rebase this off of the head of your master.  If you decide to pull this and it doesn't seem right, let me know and I'll close this PR and try again with a cleaner rebase.

**Comment by prettymuchbryce** [comment]
Can you remove the changes to files in `/bin/`? Really these should only reflect the version specified in the file name.

**Pull request merged**
